name: mcuassitant
description: A tool to help you debugging on MCU through network.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.45.0
  udp: ^5.0.1
  network_info_plus: ^2.1.3


  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
